# Generated by Django 4.2.5 on 2023-10-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.college')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.department')),
                ('elective_courses', models.ManyToManyField(blank=True, related_name='elective_programs', to='degree_checklist.course')),
            ],
        ),
        migrations.CreateModel(
            name='SectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransferEquivalency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_course_name', models.CharField(max_length=100)),
                ('external_course_id', models.CharField(max_length=100)),
                ('equivalent_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.course')),
                ('external_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.externalcollege')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDegreePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('InProgress', 'In Progress'), ('NotStarted', 'Not Started')], max_length=20)),
                ('is_completed', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.student')),
                ('transfer_equivalency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='degree_checklist.transferequivalency')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.studentrole'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('required_credits', models.IntegerField()),
                ('section_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.sectiongroup')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='section_groups',
            field=models.ManyToManyField(blank=True, to='degree_checklist.sectiongroup'),
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prerequisites', to='degree_checklist.course')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_courses', to='degree_checklist.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_credits', models.IntegerField()),
                ('courses', models.ManyToManyField(to='degree_checklist.course')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.section')),
            ],
        ),
    ]
