# Generated by Django 4.2.5 on 2023-11-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_college_documents/'),
        ),
        migrations.AddField(
            model_name='course',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_course_documents/'),
        ),
        migrations.AddField(
            model_name='courseoptiongroup',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_course_option_documents/'),
        ),
        migrations.AddField(
            model_name='department',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_department_documents/'),
        ),
        migrations.AddField(
            model_name='externalcollege',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_external_college_documents/'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_prerequisite_documents/'),
        ),
        migrations.AddField(
            model_name='program',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_program_documents/'),
        ),
        migrations.AddField(
            model_name='section',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_section_documents/'),
        ),
        migrations.AddField(
            model_name='sectiongroup',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_section_group_documents/'),
        ),
        migrations.AddField(
            model_name='semester',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_semester_documents/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_course_documents/'),
        ),
        migrations.AddField(
            model_name='studentdegreeplan',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_degree_plan_documents/'),
        ),
        migrations.AddField(
            model_name='studentrole',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_role_documents/'),
        ),
        migrations.AddField(
            model_name='transferequivalency',
            name='profile_document',
            field=models.FileField(blank=True, null=True, upload_to='student_transfers_documents/'),
        ),
    ]
